import { PrismaClient } from './generated';
export declare const db: PrismaClient<import("./generated").Prisma.PrismaClientOptions, never, import("./generated/runtime/library").DefaultArgs>;
export * from './generated';
/**
 * Get user by ID with profile
 */
export declare function getUserById(id: string): Promise<({
    profile: {
        linkedin: string | null;
        github: string | null;
        firstName: string | null;
        lastName: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        postalCode: string | null;
        userId: string;
        id: string;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        displayName: string | null;
        phone: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        address: string | null;
        website: string | null;
        portfolio: string | null;
        blog: string | null;
        bio: string | null;
        headline: string | null;
        summary: string | null;
        currentTitle: string | null;
        currentCompany: string | null;
        experienceLevel: string | null;
        yearsOfExperience: number | null;
        skills: string[];
        certifications: import("./generated/runtime/library").JsonValue | null;
        languages: import("./generated/runtime/library").JsonValue | null;
        education: import("./generated/runtime/library").JsonValue | null;
        desiredJobTypes: string[];
        desiredSalaryMin: number | null;
        desiredSalaryMax: number | null;
        preferredCurrency: string | null;
        willingToRelocate: boolean | null;
        profileVisibility: import("./generated").$Enums.ProfileVisibility;
        showEmail: boolean;
        showPhone: boolean;
    } | null;
} & {
    email: string;
    status: import("./generated").$Enums.UserStatus;
    ipAddress: string | null;
    userAgent: string | null;
    name: string | null;
    timezone: string | null;
    role: import("./generated").$Enums.UserRole;
    id: string;
    passwordHash: string | null;
    avatar: string | null;
    emailVerified: Date | null;
    lastLoginAt: Date | null;
    loginAttempts: number;
    lockedUntil: Date | null;
    dataConsent: boolean;
    consentDate: Date | null;
    dataRetentionUntil: Date | null;
    isDeleted: boolean;
    deletedAt: Date | null;
    locale: string | null;
    createdAt: Date;
    updatedAt: Date;
}) | null>;
/**
 * Get user by email with profile
 */
export declare function getUserByEmail(email: string): Promise<({
    profile: {
        linkedin: string | null;
        github: string | null;
        firstName: string | null;
        lastName: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        postalCode: string | null;
        userId: string;
        id: string;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        displayName: string | null;
        phone: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        address: string | null;
        website: string | null;
        portfolio: string | null;
        blog: string | null;
        bio: string | null;
        headline: string | null;
        summary: string | null;
        currentTitle: string | null;
        currentCompany: string | null;
        experienceLevel: string | null;
        yearsOfExperience: number | null;
        skills: string[];
        certifications: import("./generated/runtime/library").JsonValue | null;
        languages: import("./generated/runtime/library").JsonValue | null;
        education: import("./generated/runtime/library").JsonValue | null;
        desiredJobTypes: string[];
        desiredSalaryMin: number | null;
        desiredSalaryMax: number | null;
        preferredCurrency: string | null;
        willingToRelocate: boolean | null;
        profileVisibility: import("./generated").$Enums.ProfileVisibility;
        showEmail: boolean;
        showPhone: boolean;
    } | null;
} & {
    email: string;
    status: import("./generated").$Enums.UserStatus;
    ipAddress: string | null;
    userAgent: string | null;
    name: string | null;
    timezone: string | null;
    role: import("./generated").$Enums.UserRole;
    id: string;
    passwordHash: string | null;
    avatar: string | null;
    emailVerified: Date | null;
    lastLoginAt: Date | null;
    loginAttempts: number;
    lockedUntil: Date | null;
    dataConsent: boolean;
    consentDate: Date | null;
    dataRetentionUntil: Date | null;
    isDeleted: boolean;
    deletedAt: Date | null;
    locale: string | null;
    createdAt: Date;
    updatedAt: Date;
}) | null>;
/**
 * Create new user with hashed password
 */
export declare function createUser(data: {
    email: string;
    password: string;
    name?: string;
    profile?: {
        firstName?: string;
        lastName?: string;
        timezone?: string;
    };
}): Promise<{
    profile: {
        linkedin: string | null;
        github: string | null;
        firstName: string | null;
        lastName: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        postalCode: string | null;
        userId: string;
        id: string;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        displayName: string | null;
        phone: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        address: string | null;
        website: string | null;
        portfolio: string | null;
        blog: string | null;
        bio: string | null;
        headline: string | null;
        summary: string | null;
        currentTitle: string | null;
        currentCompany: string | null;
        experienceLevel: string | null;
        yearsOfExperience: number | null;
        skills: string[];
        certifications: import("./generated/runtime/library").JsonValue | null;
        languages: import("./generated/runtime/library").JsonValue | null;
        education: import("./generated/runtime/library").JsonValue | null;
        desiredJobTypes: string[];
        desiredSalaryMin: number | null;
        desiredSalaryMax: number | null;
        preferredCurrency: string | null;
        willingToRelocate: boolean | null;
        profileVisibility: import("./generated").$Enums.ProfileVisibility;
        showEmail: boolean;
        showPhone: boolean;
    } | null;
} & {
    email: string;
    status: import("./generated").$Enums.UserStatus;
    ipAddress: string | null;
    userAgent: string | null;
    name: string | null;
    timezone: string | null;
    role: import("./generated").$Enums.UserRole;
    id: string;
    passwordHash: string | null;
    avatar: string | null;
    emailVerified: Date | null;
    lastLoginAt: Date | null;
    loginAttempts: number;
    lockedUntil: Date | null;
    dataConsent: boolean;
    consentDate: Date | null;
    dataRetentionUntil: Date | null;
    isDeleted: boolean;
    deletedAt: Date | null;
    locale: string | null;
    createdAt: Date;
    updatedAt: Date;
}>;
/**
 * Authenticate user with email and password
 */
export declare function authenticateUser(email: string, password: string): Promise<({
    profile: {
        linkedin: string | null;
        github: string | null;
        firstName: string | null;
        lastName: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        postalCode: string | null;
        userId: string;
        id: string;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        displayName: string | null;
        phone: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        address: string | null;
        website: string | null;
        portfolio: string | null;
        blog: string | null;
        bio: string | null;
        headline: string | null;
        summary: string | null;
        currentTitle: string | null;
        currentCompany: string | null;
        experienceLevel: string | null;
        yearsOfExperience: number | null;
        skills: string[];
        certifications: import("./generated/runtime/library").JsonValue | null;
        languages: import("./generated/runtime/library").JsonValue | null;
        education: import("./generated/runtime/library").JsonValue | null;
        desiredJobTypes: string[];
        desiredSalaryMin: number | null;
        desiredSalaryMax: number | null;
        preferredCurrency: string | null;
        willingToRelocate: boolean | null;
        profileVisibility: import("./generated").$Enums.ProfileVisibility;
        showEmail: boolean;
        showPhone: boolean;
    } | null;
} & {
    email: string;
    status: import("./generated").$Enums.UserStatus;
    ipAddress: string | null;
    userAgent: string | null;
    name: string | null;
    timezone: string | null;
    role: import("./generated").$Enums.UserRole;
    id: string;
    passwordHash: string | null;
    avatar: string | null;
    emailVerified: Date | null;
    lastLoginAt: Date | null;
    loginAttempts: number;
    lockedUntil: Date | null;
    dataConsent: boolean;
    consentDate: Date | null;
    dataRetentionUntil: Date | null;
    isDeleted: boolean;
    deletedAt: Date | null;
    locale: string | null;
    createdAt: Date;
    updatedAt: Date;
}) | null>;
/**
 * Update user data
 */
export declare function updateUser(id: string, data: {
    name?: string;
    email?: string;
    lastLoginAt?: Date;
    profile?: {
        firstName?: string;
        lastName?: string;
        timezone?: string;
    };
}): Promise<{
    profile: {
        linkedin: string | null;
        github: string | null;
        firstName: string | null;
        lastName: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        postalCode: string | null;
        userId: string;
        id: string;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        displayName: string | null;
        phone: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        address: string | null;
        website: string | null;
        portfolio: string | null;
        blog: string | null;
        bio: string | null;
        headline: string | null;
        summary: string | null;
        currentTitle: string | null;
        currentCompany: string | null;
        experienceLevel: string | null;
        yearsOfExperience: number | null;
        skills: string[];
        certifications: import("./generated/runtime/library").JsonValue | null;
        languages: import("./generated/runtime/library").JsonValue | null;
        education: import("./generated/runtime/library").JsonValue | null;
        desiredJobTypes: string[];
        desiredSalaryMin: number | null;
        desiredSalaryMax: number | null;
        preferredCurrency: string | null;
        willingToRelocate: boolean | null;
        profileVisibility: import("./generated").$Enums.ProfileVisibility;
        showEmail: boolean;
        showPhone: boolean;
    } | null;
} & {
    email: string;
    status: import("./generated").$Enums.UserStatus;
    ipAddress: string | null;
    userAgent: string | null;
    name: string | null;
    timezone: string | null;
    role: import("./generated").$Enums.UserRole;
    id: string;
    passwordHash: string | null;
    avatar: string | null;
    emailVerified: Date | null;
    lastLoginAt: Date | null;
    loginAttempts: number;
    lockedUntil: Date | null;
    dataConsent: boolean;
    consentDate: Date | null;
    dataRetentionUntil: Date | null;
    isDeleted: boolean;
    deletedAt: Date | null;
    locale: string | null;
    createdAt: Date;
    updatedAt: Date;
}>;
/**
 * Delete user (soft delete by updating status)
 */
export declare function deleteUser(id: string): Promise<{
    email: string;
    status: import("./generated").$Enums.UserStatus;
    ipAddress: string | null;
    userAgent: string | null;
    name: string | null;
    timezone: string | null;
    role: import("./generated").$Enums.UserRole;
    id: string;
    passwordHash: string | null;
    avatar: string | null;
    emailVerified: Date | null;
    lastLoginAt: Date | null;
    loginAttempts: number;
    lockedUntil: Date | null;
    dataConsent: boolean;
    consentDate: Date | null;
    dataRetentionUntil: Date | null;
    isDeleted: boolean;
    deletedAt: Date | null;
    locale: string | null;
    createdAt: Date;
    updatedAt: Date;
}>;
/**
 * Create a new job
 */
export declare function createJob(data: {
    title: string;
    companyId: string;
    sourceUrl?: string;
    description?: string;
    location?: string;
    salaryMin?: number;
    salaryMax?: number;
    type?: 'FULL_TIME' | 'PART_TIME' | 'CONTRACT' | 'FREELANCE' | 'INTERNSHIP' | 'TEMPORARY' | 'VOLUNTEER' | 'APPRENTICESHIP';
    level?: 'ENTRY' | 'JUNIOR' | 'MID' | 'SENIOR' | 'LEAD' | 'PRINCIPAL' | 'STAFF' | 'MANAGER' | 'SENIOR_MANAGER' | 'DIRECTOR' | 'SENIOR_DIRECTOR' | 'VP' | 'SVP' | 'C_LEVEL' | 'FOUNDER';
    remoteType?: 'ONSITE' | 'REMOTE' | 'HYBRID' | 'FLEXIBLE';
    skills?: string[];
    requirements?: string;
}): Promise<{
    remote: boolean;
    source: import("./generated").$Enums.JobSource;
    status: import("./generated").$Enums.JobStatus;
    type: import("./generated").$Enums.JobType;
    description: string;
    city: string | null;
    state: string | null;
    country: string | null;
    coordinates: import("./generated/runtime/library").JsonValue | null;
    timeZone: string | null;
    id: string;
    expiresAt: Date | null;
    location: string | null;
    createdAt: Date;
    updatedAt: Date;
    skills: string[];
    languages: string[];
    education: string | null;
    title: string;
    requirements: string | null;
    benefits: string | null;
    level: import("./generated").$Enums.JobLevel;
    department: string | null;
    category: import("./generated").$Enums.JobCategory;
    remoteType: import("./generated").$Enums.RemoteType;
    salaryMin: number | null;
    salaryMax: number | null;
    currency: string | null;
    salaryType: import("./generated").$Enums.SalaryType | null;
    equity: string | null;
    bonus: string | null;
    experienceYears: number | null;
    companyId: string;
    externalId: string | null;
    sourceUrl: string | null;
    applyUrl: string | null;
    keywords: string[];
    tags: string[];
    qualityScore: number | null;
    isVerified: boolean;
    verifiedAt: Date | null;
    isActive: boolean;
    isFeatured: boolean;
    isUrgent: boolean;
    postedAt: Date | null;
    lastScrapedAt: Date | null;
    viewCount: number;
    applicationCount: number;
    rightSwipeCount: number;
    leftSwipeCount: number;
}>;
/**
 * Get job by ID
 */
export declare function getJobById(id: string): Promise<({
    applications: ({
        user: {
            email: string;
            name: string | null;
            id: string;
        };
    } & {
        source: import("./generated").$Enums.ApplicationSource;
        status: import("./generated").$Enums.ApplicationStatus;
        userId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        externalId: string | null;
        jobPostingId: string;
        resumeId: string | null;
        priority: import("./generated").$Enums.ApplicationPriority;
        coverLetter: string | null;
        customFields: import("./generated/runtime/library").JsonValue | null;
        notes: string | null;
        customResume: import("./generated/runtime/library").JsonValue | null;
        resumeVersion: string | null;
        appliedAt: Date | null;
        viewedAt: Date | null;
        responseAt: Date | null;
        interviewAt: Date | null;
        followUpAt: Date | null;
        rejectedAt: Date | null;
        acceptedAt: Date | null;
        atsUrl: string | null;
        confirmationNumber: string | null;
        automationStatus: import("./generated").$Enums.AutomationStatus | null;
        automationAttempts: number;
        automationData: import("./generated/runtime/library").JsonValue | null;
        lastAutomationAt: Date | null;
        lastContactAt: Date | null;
        contactMethod: string | null;
        recruiterName: string | null;
        recruiterEmail: string | null;
        recruiterPhone: string | null;
        responseTime: number | null;
        interviewCount: number;
        matchScore: number | null;
        appliedVia: string | null;
    })[];
} & {
    remote: boolean;
    source: import("./generated").$Enums.JobSource;
    status: import("./generated").$Enums.JobStatus;
    type: import("./generated").$Enums.JobType;
    description: string;
    city: string | null;
    state: string | null;
    country: string | null;
    coordinates: import("./generated/runtime/library").JsonValue | null;
    timeZone: string | null;
    id: string;
    expiresAt: Date | null;
    location: string | null;
    createdAt: Date;
    updatedAt: Date;
    skills: string[];
    languages: string[];
    education: string | null;
    title: string;
    requirements: string | null;
    benefits: string | null;
    level: import("./generated").$Enums.JobLevel;
    department: string | null;
    category: import("./generated").$Enums.JobCategory;
    remoteType: import("./generated").$Enums.RemoteType;
    salaryMin: number | null;
    salaryMax: number | null;
    currency: string | null;
    salaryType: import("./generated").$Enums.SalaryType | null;
    equity: string | null;
    bonus: string | null;
    experienceYears: number | null;
    companyId: string;
    externalId: string | null;
    sourceUrl: string | null;
    applyUrl: string | null;
    keywords: string[];
    tags: string[];
    qualityScore: number | null;
    isVerified: boolean;
    verifiedAt: Date | null;
    isActive: boolean;
    isFeatured: boolean;
    isUrgent: boolean;
    postedAt: Date | null;
    lastScrapedAt: Date | null;
    viewCount: number;
    applicationCount: number;
    rightSwipeCount: number;
    leftSwipeCount: number;
}) | null>;
/**
 * Get jobs with pagination and filters
 */
export declare function getJobs(options?: {
    page?: number;
    limit?: number;
    search?: string;
    jobType?: string;
    remoteType?: string;
    minSalary?: number;
    maxSalary?: number;
    skills?: string[];
}): Promise<{
    jobs: {
        remote: boolean;
        source: import("./generated").$Enums.JobSource;
        status: import("./generated").$Enums.JobStatus;
        type: import("./generated").$Enums.JobType;
        description: string;
        city: string | null;
        state: string | null;
        country: string | null;
        coordinates: import("./generated/runtime/library").JsonValue | null;
        timeZone: string | null;
        id: string;
        expiresAt: Date | null;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        skills: string[];
        languages: string[];
        education: string | null;
        title: string;
        requirements: string | null;
        benefits: string | null;
        level: import("./generated").$Enums.JobLevel;
        department: string | null;
        category: import("./generated").$Enums.JobCategory;
        remoteType: import("./generated").$Enums.RemoteType;
        salaryMin: number | null;
        salaryMax: number | null;
        currency: string | null;
        salaryType: import("./generated").$Enums.SalaryType | null;
        equity: string | null;
        bonus: string | null;
        experienceYears: number | null;
        companyId: string;
        externalId: string | null;
        sourceUrl: string | null;
        applyUrl: string | null;
        keywords: string[];
        tags: string[];
        qualityScore: number | null;
        isVerified: boolean;
        verifiedAt: Date | null;
        isActive: boolean;
        isFeatured: boolean;
        isUrgent: boolean;
        postedAt: Date | null;
        lastScrapedAt: Date | null;
        viewCount: number;
        applicationCount: number;
        rightSwipeCount: number;
        leftSwipeCount: number;
    }[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        pages: number;
    };
}>;
/**
 * Create job application
 */
export declare function createApplication(data: {
    userId: string;
    jobId: string;
    resumeId?: string;
    coverLetter?: string;
    customFields?: any;
    source?: 'MANUAL' | 'AUTOMATION' | 'BULK_APPLY' | 'REFERRAL' | 'RECRUITER' | 'COMPANY_OUTREACH';
}): Promise<{
    user: {
        email: string;
        name: string | null;
        id: string;
    };
    jobPosting: {
        remote: boolean;
        source: import("./generated").$Enums.JobSource;
        status: import("./generated").$Enums.JobStatus;
        type: import("./generated").$Enums.JobType;
        description: string;
        city: string | null;
        state: string | null;
        country: string | null;
        coordinates: import("./generated/runtime/library").JsonValue | null;
        timeZone: string | null;
        id: string;
        expiresAt: Date | null;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        skills: string[];
        languages: string[];
        education: string | null;
        title: string;
        requirements: string | null;
        benefits: string | null;
        level: import("./generated").$Enums.JobLevel;
        department: string | null;
        category: import("./generated").$Enums.JobCategory;
        remoteType: import("./generated").$Enums.RemoteType;
        salaryMin: number | null;
        salaryMax: number | null;
        currency: string | null;
        salaryType: import("./generated").$Enums.SalaryType | null;
        equity: string | null;
        bonus: string | null;
        experienceYears: number | null;
        companyId: string;
        externalId: string | null;
        sourceUrl: string | null;
        applyUrl: string | null;
        keywords: string[];
        tags: string[];
        qualityScore: number | null;
        isVerified: boolean;
        verifiedAt: Date | null;
        isActive: boolean;
        isFeatured: boolean;
        isUrgent: boolean;
        postedAt: Date | null;
        lastScrapedAt: Date | null;
        viewCount: number;
        applicationCount: number;
        rightSwipeCount: number;
        leftSwipeCount: number;
    };
    resume: {
        name: string;
        version: number;
        userId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        title: string | null;
        viewCount: number;
        applicationCount: number;
        templateId: string | null;
        content: import("./generated/runtime/library").JsonValue;
        sections: import("./generated/runtime/library").JsonValue;
        metadata: import("./generated/runtime/library").JsonValue | null;
        pdfUrl: string | null;
        docxUrl: string | null;
        htmlUrl: string | null;
        fileSize: number | null;
        pageCount: number | null;
        lastGenerated: Date | null;
        parentResumeId: string | null;
        isDefault: boolean;
        visibility: import("./generated").$Enums.ResumeVisibility;
        shareToken: string | null;
        downloadCount: number;
        aiEnhanced: boolean;
        enhancementData: import("./generated/runtime/library").JsonValue | null;
        completeness: number | null;
        readabilityScore: number | null;
        keywordMatch: number | null;
    } | null;
} & {
    source: import("./generated").$Enums.ApplicationSource;
    status: import("./generated").$Enums.ApplicationStatus;
    userId: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    externalId: string | null;
    jobPostingId: string;
    resumeId: string | null;
    priority: import("./generated").$Enums.ApplicationPriority;
    coverLetter: string | null;
    customFields: import("./generated/runtime/library").JsonValue | null;
    notes: string | null;
    customResume: import("./generated/runtime/library").JsonValue | null;
    resumeVersion: string | null;
    appliedAt: Date | null;
    viewedAt: Date | null;
    responseAt: Date | null;
    interviewAt: Date | null;
    followUpAt: Date | null;
    rejectedAt: Date | null;
    acceptedAt: Date | null;
    atsUrl: string | null;
    confirmationNumber: string | null;
    automationStatus: import("./generated").$Enums.AutomationStatus | null;
    automationAttempts: number;
    automationData: import("./generated/runtime/library").JsonValue | null;
    lastAutomationAt: Date | null;
    lastContactAt: Date | null;
    contactMethod: string | null;
    recruiterName: string | null;
    recruiterEmail: string | null;
    recruiterPhone: string | null;
    responseTime: number | null;
    interviewCount: number;
    matchScore: number | null;
    appliedVia: string | null;
}>;
/**
 * Get user applications
 */
export declare function getUserApplications(userId: string, options?: {
    page?: number;
    limit?: number;
    status?: string;
}): Promise<{
    applications: ({
        jobPosting: {
            remote: boolean;
            source: import("./generated").$Enums.JobSource;
            status: import("./generated").$Enums.JobStatus;
            type: import("./generated").$Enums.JobType;
            description: string;
            city: string | null;
            state: string | null;
            country: string | null;
            coordinates: import("./generated/runtime/library").JsonValue | null;
            timeZone: string | null;
            id: string;
            expiresAt: Date | null;
            location: string | null;
            createdAt: Date;
            updatedAt: Date;
            skills: string[];
            languages: string[];
            education: string | null;
            title: string;
            requirements: string | null;
            benefits: string | null;
            level: import("./generated").$Enums.JobLevel;
            department: string | null;
            category: import("./generated").$Enums.JobCategory;
            remoteType: import("./generated").$Enums.RemoteType;
            salaryMin: number | null;
            salaryMax: number | null;
            currency: string | null;
            salaryType: import("./generated").$Enums.SalaryType | null;
            equity: string | null;
            bonus: string | null;
            experienceYears: number | null;
            companyId: string;
            externalId: string | null;
            sourceUrl: string | null;
            applyUrl: string | null;
            keywords: string[];
            tags: string[];
            qualityScore: number | null;
            isVerified: boolean;
            verifiedAt: Date | null;
            isActive: boolean;
            isFeatured: boolean;
            isUrgent: boolean;
            postedAt: Date | null;
            lastScrapedAt: Date | null;
            viewCount: number;
            applicationCount: number;
            rightSwipeCount: number;
            leftSwipeCount: number;
        };
        resume: {
            name: string;
            version: number;
            userId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title: string | null;
            viewCount: number;
            applicationCount: number;
            templateId: string | null;
            content: import("./generated/runtime/library").JsonValue;
            sections: import("./generated/runtime/library").JsonValue;
            metadata: import("./generated/runtime/library").JsonValue | null;
            pdfUrl: string | null;
            docxUrl: string | null;
            htmlUrl: string | null;
            fileSize: number | null;
            pageCount: number | null;
            lastGenerated: Date | null;
            parentResumeId: string | null;
            isDefault: boolean;
            visibility: import("./generated").$Enums.ResumeVisibility;
            shareToken: string | null;
            downloadCount: number;
            aiEnhanced: boolean;
            enhancementData: import("./generated/runtime/library").JsonValue | null;
            completeness: number | null;
            readabilityScore: number | null;
            keywordMatch: number | null;
        } | null;
    } & {
        source: import("./generated").$Enums.ApplicationSource;
        status: import("./generated").$Enums.ApplicationStatus;
        userId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        externalId: string | null;
        jobPostingId: string;
        resumeId: string | null;
        priority: import("./generated").$Enums.ApplicationPriority;
        coverLetter: string | null;
        customFields: import("./generated/runtime/library").JsonValue | null;
        notes: string | null;
        customResume: import("./generated/runtime/library").JsonValue | null;
        resumeVersion: string | null;
        appliedAt: Date | null;
        viewedAt: Date | null;
        responseAt: Date | null;
        interviewAt: Date | null;
        followUpAt: Date | null;
        rejectedAt: Date | null;
        acceptedAt: Date | null;
        atsUrl: string | null;
        confirmationNumber: string | null;
        automationStatus: import("./generated").$Enums.AutomationStatus | null;
        automationAttempts: number;
        automationData: import("./generated/runtime/library").JsonValue | null;
        lastAutomationAt: Date | null;
        lastContactAt: Date | null;
        contactMethod: string | null;
        recruiterName: string | null;
        recruiterEmail: string | null;
        recruiterPhone: string | null;
        responseTime: number | null;
        interviewCount: number;
        matchScore: number | null;
        appliedVia: string | null;
    })[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        pages: number;
    };
}>;
/**
 * Update application status
 */
export declare function updateApplicationStatus(id: string, status: 'DRAFT' | 'QUEUED' | 'APPLYING' | 'APPLIED' | 'APPLICATION_ERROR' | 'VIEWED' | 'SCREENING' | 'PHONE_SCREEN' | 'INTERVIEW_SCHEDULED' | 'FIRST_INTERVIEW' | 'SECOND_INTERVIEW' | 'FINAL_INTERVIEW' | 'TECHNICAL_ASSESSMENT' | 'TAKE_HOME_PROJECT' | 'REFERENCE_CHECK' | 'BACKGROUND_CHECK' | 'OFFER_PENDING' | 'OFFER_RECEIVED' | 'OFFER_ACCEPTED' | 'OFFER_DECLINED' | 'REJECTED' | 'WITHDRAWN' | 'GHOSTED' | 'ARCHIVED', notes?: string): Promise<{
    user: {
        email: string;
        name: string | null;
        id: string;
    };
    jobPosting: {
        remote: boolean;
        source: import("./generated").$Enums.JobSource;
        status: import("./generated").$Enums.JobStatus;
        type: import("./generated").$Enums.JobType;
        description: string;
        city: string | null;
        state: string | null;
        country: string | null;
        coordinates: import("./generated/runtime/library").JsonValue | null;
        timeZone: string | null;
        id: string;
        expiresAt: Date | null;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        skills: string[];
        languages: string[];
        education: string | null;
        title: string;
        requirements: string | null;
        benefits: string | null;
        level: import("./generated").$Enums.JobLevel;
        department: string | null;
        category: import("./generated").$Enums.JobCategory;
        remoteType: import("./generated").$Enums.RemoteType;
        salaryMin: number | null;
        salaryMax: number | null;
        currency: string | null;
        salaryType: import("./generated").$Enums.SalaryType | null;
        equity: string | null;
        bonus: string | null;
        experienceYears: number | null;
        companyId: string;
        externalId: string | null;
        sourceUrl: string | null;
        applyUrl: string | null;
        keywords: string[];
        tags: string[];
        qualityScore: number | null;
        isVerified: boolean;
        verifiedAt: Date | null;
        isActive: boolean;
        isFeatured: boolean;
        isUrgent: boolean;
        postedAt: Date | null;
        lastScrapedAt: Date | null;
        viewCount: number;
        applicationCount: number;
        rightSwipeCount: number;
        leftSwipeCount: number;
    };
} & {
    source: import("./generated").$Enums.ApplicationSource;
    status: import("./generated").$Enums.ApplicationStatus;
    userId: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    externalId: string | null;
    jobPostingId: string;
    resumeId: string | null;
    priority: import("./generated").$Enums.ApplicationPriority;
    coverLetter: string | null;
    customFields: import("./generated/runtime/library").JsonValue | null;
    notes: string | null;
    customResume: import("./generated/runtime/library").JsonValue | null;
    resumeVersion: string | null;
    appliedAt: Date | null;
    viewedAt: Date | null;
    responseAt: Date | null;
    interviewAt: Date | null;
    followUpAt: Date | null;
    rejectedAt: Date | null;
    acceptedAt: Date | null;
    atsUrl: string | null;
    confirmationNumber: string | null;
    automationStatus: import("./generated").$Enums.AutomationStatus | null;
    automationAttempts: number;
    automationData: import("./generated/runtime/library").JsonValue | null;
    lastAutomationAt: Date | null;
    lastContactAt: Date | null;
    contactMethod: string | null;
    recruiterName: string | null;
    recruiterEmail: string | null;
    recruiterPhone: string | null;
    responseTime: number | null;
    interviewCount: number;
    matchScore: number | null;
    appliedVia: string | null;
}>;
/**
 * Record user job swipe
 */
export declare function createUserJobSwipe(data: {
    userId: string;
    jobId: string;
    swipedRight: boolean;
}): Promise<{
    jobPosting: {
        remote: boolean;
        source: import("./generated").$Enums.JobSource;
        status: import("./generated").$Enums.JobStatus;
        type: import("./generated").$Enums.JobType;
        description: string;
        city: string | null;
        state: string | null;
        country: string | null;
        coordinates: import("./generated/runtime/library").JsonValue | null;
        timeZone: string | null;
        id: string;
        expiresAt: Date | null;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        skills: string[];
        languages: string[];
        education: string | null;
        title: string;
        requirements: string | null;
        benefits: string | null;
        level: import("./generated").$Enums.JobLevel;
        department: string | null;
        category: import("./generated").$Enums.JobCategory;
        remoteType: import("./generated").$Enums.RemoteType;
        salaryMin: number | null;
        salaryMax: number | null;
        currency: string | null;
        salaryType: import("./generated").$Enums.SalaryType | null;
        equity: string | null;
        bonus: string | null;
        experienceYears: number | null;
        companyId: string;
        externalId: string | null;
        sourceUrl: string | null;
        applyUrl: string | null;
        keywords: string[];
        tags: string[];
        qualityScore: number | null;
        isVerified: boolean;
        verifiedAt: Date | null;
        isActive: boolean;
        isFeatured: boolean;
        isUrgent: boolean;
        postedAt: Date | null;
        lastScrapedAt: Date | null;
        viewCount: number;
        applicationCount: number;
        rightSwipeCount: number;
        leftSwipeCount: number;
    };
} & {
    ipAddress: string | null;
    userAgent: string | null;
    direction: import("./generated").$Enums.SwipeDirection;
    userId: string;
    id: string;
    deviceType: string | null;
    location: string | null;
    createdAt: Date;
    updatedAt: Date;
    jobPostingId: string;
    matchScore: number | null;
    confidence: number | null;
    sessionId: string | null;
    position: number | null;
    timeSpent: number | null;
    matchFactors: import("./generated/runtime/library").JsonValue | null;
    userFeedback: string | null;
    isCorrectMatch: boolean | null;
}>;
/**
 * Get user's swiped jobs
 */
export declare function getUserSwipedJobs(userId: string, swipedRight?: boolean): Promise<({
    jobPosting: {
        remote: boolean;
        source: import("./generated").$Enums.JobSource;
        status: import("./generated").$Enums.JobStatus;
        type: import("./generated").$Enums.JobType;
        description: string;
        city: string | null;
        state: string | null;
        country: string | null;
        coordinates: import("./generated/runtime/library").JsonValue | null;
        timeZone: string | null;
        id: string;
        expiresAt: Date | null;
        location: string | null;
        createdAt: Date;
        updatedAt: Date;
        skills: string[];
        languages: string[];
        education: string | null;
        title: string;
        requirements: string | null;
        benefits: string | null;
        level: import("./generated").$Enums.JobLevel;
        department: string | null;
        category: import("./generated").$Enums.JobCategory;
        remoteType: import("./generated").$Enums.RemoteType;
        salaryMin: number | null;
        salaryMax: number | null;
        currency: string | null;
        salaryType: import("./generated").$Enums.SalaryType | null;
        equity: string | null;
        bonus: string | null;
        experienceYears: number | null;
        companyId: string;
        externalId: string | null;
        sourceUrl: string | null;
        applyUrl: string | null;
        keywords: string[];
        tags: string[];
        qualityScore: number | null;
        isVerified: boolean;
        verifiedAt: Date | null;
        isActive: boolean;
        isFeatured: boolean;
        isUrgent: boolean;
        postedAt: Date | null;
        lastScrapedAt: Date | null;
        viewCount: number;
        applicationCount: number;
        rightSwipeCount: number;
        leftSwipeCount: number;
    };
} & {
    ipAddress: string | null;
    userAgent: string | null;
    direction: import("./generated").$Enums.SwipeDirection;
    userId: string;
    id: string;
    deviceType: string | null;
    location: string | null;
    createdAt: Date;
    updatedAt: Date;
    jobPostingId: string;
    matchScore: number | null;
    confidence: number | null;
    sessionId: string | null;
    position: number | null;
    timeSpent: number | null;
    matchFactors: import("./generated/runtime/library").JsonValue | null;
    userFeedback: string | null;
    isCorrectMatch: boolean | null;
})[]>;
/**
 * Database health check
 */
export declare function checkDatabaseHealth(): Promise<{
    status: string;
    timestamp: Date;
    error?: undefined;
} | {
    status: string;
    error: string;
    timestamp: Date;
}>;
/**
 * Get database statistics
 */
export declare function getDatabaseStats(): Promise<{
    users: number;
    jobs: number;
    applications: number;
    timestamp: Date;
}>;
/**
 * Graceful shutdown
 */
export declare function disconnectDatabase(): Promise<void>;
//# sourceMappingURL=index.d.ts.map